version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: productosdb
      MYSQL_USER: ulises
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"